# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

# [remote.github]
# owner = "orhun"
# repo = "git-cliff"
# token = ""

[changelog]
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        {% if commit.scope -%}
            - **({{commit.scope}})** {{ commit.message | upper_first | trim }}\
        {% else -%}
            - {{ commit.message | upper_first | trim }}\
        {% endif -%}
        {% if commit.remote.pr_number %} in \
            [#{{ commit.remote.pr_number }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/pull/{{ commit.remote.pr_number }}) \
        {%- endif -%}
        {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif %}
    {% endfor %}
{% endfor %}
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true
# A Tera template to be rendered as the changelog's footer.
# See https://keats.github.io/tera/docs/#introduction
footer = """
<!-- generated by git-cliff -->
"""
# An array of regex based postprocessors to modify the changelog.
# Replace the placeholder `<REPO>` with a URL.
postprocessors = []

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = false
# Split commits on newlines, treating each line as an individual commit.
split_commits = false
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->:rocket: New features" },
    { message = "^fix", group = "<!-- 1 -->:bug: Bug fixes" },
    { message = "^docs", group = "<!-- 2 -->:page_facing_up: Documentation" },
    { message = "^perf", group = "<!-- 3 -->:zap: Performance" },
    { message = "^chore", group = "<!-- 4 -->:wrench: Miscellaneous" },
    { message = "^refactor", group = "<!-- 5 -->:recycle: Refactoring" },
    { message = "^style", group = "<!-- 6 -->:art: Styling" },
    { message = "^test", group = "<!-- 7 -->:white_check_mark: Testing" },
    { message = ".*", group = "<!-- 8 -->:package: Other" },
]
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" }]
# Exclude commits that are not matched by any commit parser.
filter_commits = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "newest"
